var codes = 
["af","al","dz","ao","ag","ar","am","au","at","az","bs","bh","bd","bb","by","be","bz","bj","bt","bo","ba","bw","br","bn","bg","bf","bi","kh","cm","ca","cv","cf","td","cl","cn","co","cu","km","cd","cg","cr","ci","hr","cy","cz","dk","dj","dm","do","ec","eg","sv","gq","er","ee","et","fj","fi","fk","fr","ga","gl","gm","ge","de","gh","gr","gd","gf","gt","gn","gw","gy","ht","hn","hk","hu","is","in","id","ir","iq","ie","il","it","jm","jp","jo","kz","ke","ki","kp","kr","undefined","kw","kg","la","lv","lb","ls","lr","ly","lt","lu","mk","mg","mw","my","mv","ml","mt","mr","mu","mx","md","mn","me","ma","mz","mm","na","np","nl","nz","ni","ne","nc","ng","no","om","pk","pa","pg","py","pe","ph","pl","pt","qa","ro","ru","rw","ws","st","sa","sn","re","rs","sc","sl","so","sg","sk","si","sb","za","es","lk","kn","lc","vc","sd","sr","sz","se","ch","sy","tw","tj","tz","th","tl","tg","to","tt","tn","tr","tm","ug","ua","ae","gb","us","uy","uz","vu","ve","vn","ye","zm","zw"];
var arr = [];
// Randomize ranks for all regions and then sort them to present
for (i = 0;i < codes.length; i++) {
    rank = Math.random()*1000000;
	var objecto = {"code":codes[i],"rank":rank};
    arr.push(objecto);
}
//console.log(arr);

var codeSort = function(a,b) {
  if(a.rank == b.rank) {
      return 0;
  } else if (a.rank > b.rank) {
      return 1;
  } else {
      return -1;
  }
};

arr.sort(codeSort);
//console.log(arr);
mapsequence = arr;
regions = [
{"Code":"AE","Country":"United Arab Emirates"},
{"Code":"AF","Country":"Afghanistan"},
{"Code":"AG","Country":"Antigua and Barbuda"},
{"Code":"AL","Country":"Albania"},
{"Code":"AM","Country":"Armenia"},
{"Code":"AO","Country":"Angola"},
{"Code":"AR","Country":"Argentina"},
{"Code":"AT","Country":"Austria"},
{"Code":"AU","Country":"Australia"},
{"Code":"AZ","Country":"Azerbaijan"},
{"Code":"BA","Country":"Bosnia and Herzegovina"},
{"Code":"BB","Country":"Barbados"},
{"Code":"BD","Country":"Bangladesh"},
{"Code":"BE","Country":"Belgium"},
{"Code":"BF","Country":"Burkina Faso"},
{"Code":"BG","Country":"Bulgaria"},
{"Code":"BI","Country":"Burundi"},
{"Code":"BJ","Country":"Benin"},
{"Code":"BN","Country":"Brunei Darussalam"},
{"Code":"BO","Country":"Bolivia"},
{"Code":"BR","Country":"Brazil"},
{"Code":"BS","Country":"Bahamas"},
{"Code":"BT","Country":"Bhutan"},
{"Code":"BW","Country":"Botswana"},
{"Code":"BY","Country":"Belarus"},
{"Code":"BZ","Country":"Belize"},
{"Code":"CA","Country":"Canada"},
{"Code":"CD","Country":"The Democratic Republic Of The Congo"},
{"Code":"CF","Country":"Central African Republic"},
{"Code":"CG","Country":"Republic Of The Congo"},
{"Code":"CH","Country":"Switzerland"},
{"Code":"CI","Country":"Cote d'Ivoire"},
{"Code":"CL","Country":"Chile"},
{"Code":"CM","Country":"Cameroon"},
{"Code":"CN","Country":"China"},
{"Code":"CO","Country":"Colombia"},
{"Code":"CR","Country":"Costa Rica"},
{"Code":"CU","Country":"Cuba"},
{"Code":"CV","Country":"Cape Verde"},
{"Code":"CY","Country":"Cyprus"},
{"Code":"CZ","Country":"Czech Republic"},
{"Code":"DE","Country":"Germany"},
{"Code":"DJ","Country":"Djibouti"},
{"Code":"DK","Country":"Denmark"},
{"Code":"DM","Country":"Dominica"},
{"Code":"DO","Country":"Dominican Republic"},
{"Code":"DZ","Country":"Algeria"},
{"Code":"EC","Country":"Ecuador"},
{"Code":"EE","Country":"Estonia"},
{"Code":"EG","Country":"Egypt"},
{"Code":"ER","Country":"Eritrea"},
{"Code":"ES","Country":"Spain"},
{"Code":"ET","Country":"Ethiopia"},
{"Code":"FI","Country":"Finland"},
{"Code":"FJ","Country":"Fiji"},
{"Code":"FK","Country":"Falkland Islands"},
{"Code":"FR","Country":"France"},
{"Code":"GA","Country":"Gabon"},
{"Code":"GB","Country":"United Kingdom"},
{"Code":"GD","Country":"Grenada"},
{"Code":"GE","Country":"Georgia"},
{"Code":"GF","Country":"French Guiana"},
{"Code":"GH","Country":"Ghana"},
{"Code":"GL","Country":"Greenland"},
{"Code":"GM","Country":"Gambia"},
{"Code":"GN","Country":"Guinea"},
{"Code":"GQ","Country":"Equatorial Guinea"},
{"Code":"GR","Country":"Greece"},
{"Code":"GT","Country":"Guatemala"},
{"Code":"GW","Country":"Guinea-Bissau"},
{"Code":"GY","Country":"Guyana"},
{"Code":"HN","Country":"Honduras"},
{"Code":"HR","Country":"Croatia"},
{"Code":"HT","Country":"Haiti"},
{"Code":"HU","Country":"Hungary"},
{"Code":"ID","Country":"Indonesia"},
{"Code":"IE","Country":"Ireland"},
{"Code":"IL","Country":"Israel"},
{"Code":"IN","Country":"India"},
{"Code":"IQ","Country":"Iraq"},
{"Code":"IR","Country":"Iran"},
{"Code":"IS","Country":"Iceland"},
{"Code":"IT","Country":"Italy"},
{"Code":"JM","Country":"Jamaica"},
{"Code":"JO","Country":"Jordan"},
{"Code":"JP","Country":"Japan"},
{"Code":"KE","Country":"Kenya"},
{"Code":"KG","Country":"Kyrgyzstan"},
{"Code":"KH","Country":"Cambodia"},
{"Code":"KM","Country":"Comoros"},
{"Code":"KN","Country":"Saint Kitts and Nevis"},
{"Code":"KP","Country":"North Korea"},
{"Code":"KR","Country":"South Korea"},
{"Code":"KW","Country":"Kuwait"},
{"Code":"KZ","Country":"Kazakhstan"},
{"Code":"LA","Country":"Lao People's Democratic Republic"},
{"Code":"LB","Country":"Lebanon"},
{"Code":"LC","Country":"Saint Lucia"},
{"Code":"LK","Country":"Sri Lanka"},
{"Code":"LR","Country":"Liberia"},
{"Code":"LS","Country":"Lesotho"},
{"Code":"LT","Country":"Lithuania"},
{"Code":"LV","Country":"Latvia"},
{"Code":"LY","Country":"Libya"},
{"Code":"MA","Country":"Morocco"},
{"Code":"MD","Country":"Republic of Moldova"},
{"Code":"MG","Country":"Madagascar"},
{"Code":"MK","Country":"Macedonia"},
{"Code":"ML","Country":"Mali"},
{"Code":"MM","Country":"Myanmar"},
{"Code":"MN","Country":"Mongolia"},
{"Code":"MR","Country":"Mauritania"},
{"Code":"MT","Country":"Malta"},
{"Code":"MU","Country":"Mauritius"},
{"Code":"MV","Country":"Maldives"},
{"Code":"MW","Country":"Malawi"},
{"Code":"MX","Country":"Mexico"},
{"Code":"MY","Country":"Malaysia"},
{"Code":"MZ","Country":"Mozambique"},
{"Code":"NA","Country":"Namibia"},
{"Code":"NC","Country":"New Caledonia"},
{"Code":"NE","Country":"Niger"},
{"Code":"NG","Country":"Nigeria"},
{"Code":"NI","Country":"Nicaragua"},
{"Code":"NL","Country":"Netherlands"},
{"Code":"NO","Country":"Norway"},
{"Code":"NP","Country":"Nepal"},
{"Code":"NZ","Country":"New Zealand"},
{"Code":"OM","Country":"Oman"},
{"Code":"PA","Country":"Panama"},
{"Code":"PE","Country":"Peru"},
{"Code":"PF","Country":"French Polynesia"},
{"Code":"PG","Country":"Papua New Guinea"},
{"Code":"PH","Country":"Philippines"},
{"Code":"PK","Country":"Pakistan"},
{"Code":"PL","Country":"Poland"},
{"Code":"PT","Country":"Portugal"},
{"Code":"PY","Country":"Paraguay"},
{"Code":"QA","Country":"Qatar"},
{"Code":"RE","Country":"Reunion"},
{"Code":"RO","Country":"Romania"},
{"Code":"RS","Country":"Serbia"},
{"Code":"RU","Country":"Russian Federation"},
{"Code":"RW","Country":"Rwanda"},
{"Code":"SA","Country":"Saudi Arabia"},
{"Code":"SB","Country":"Solomon Islands"},
{"Code":"SC","Country":"Seychelles"},
{"Code":"SD","Country":"Sudan"},
{"Code":"SE","Country":"Sweden"},
{"Code":"SI","Country":"Slovenia"},
{"Code":"SK","Country":"Slovakia"},
{"Code":"SL","Country":"Sierra Leone"},
{"Code":"SN","Country":"Senegal"},
{"Code":"SO","Country":"Somalia"},
{"Code":"SR","Country":"Suriname"},
{"Code":"ST","Country":"Sao Tome and Principe"},
{"Code":"SV","Country":"El Salvador"},
{"Code":"SY","Country":"Syrian Arab Republic"},
{"Code":"SZ","Country":"Swaziland"},
{"Code":"TD","Country":"Chad"},
{"Code":"TG","Country":"Togo"},
{"Code":"TH","Country":"Thailand"},
{"Code":"TJ","Country":"Tajikistan"},
{"Code":"TL","Country":"Timor-Leste"},
{"Code":"TM","Country":"Turkmenistan"},
{"Code":"TN","Country":"Tunisia"},
{"Code":"TR","Country":"Turkey"},
{"Code":"TT","Country":"Trinidad and Tobago"},
{"Code":"TW","Country":"Taiwan"},
{"Code":"TZ","Country":"United Republic Of Tanzania"},
{"Code":"UA","Country":"Ukraine"},
{"Code":"UG","Country":"Uganda"},
{"Code":"US","Country":"United States of America"},
{"Code":"UY","Country":"Uruguay"},
{"Code":"UZ","Country":"Uzbekistan"},
{"Code":"VE","Country":"Venezuela"},
{"Code":"VN","Country":"Vietnam"},
{"Code":"VU","Country":"Vanuatu"},
{"Code":"YE","Country":"Yemen"},
{"Code":"ZA","Country":"South Africa"},
{"Code":"ZM","Country":"Zambia"},
{"Code":"ZW","Country":"Zimbabwe"}
]